version: "3.8"

services:
  tb-upgrader:
    build:
      context: .
      dockerfile: Dockerfile.tb-upgrader
    container_name: tb-upgrader
    volumes:
      - /etc/thingsboard:/etc/thingsboard
      - /usr/share/thingsboard:/usr/share/thingsboard
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.17.0.1:5432/thingsboard
      - SPRING_DATASOURCE_USERNAME=nethmi
      - SPRING_DATASOURCE_PASSWORD=123456
