FROM thingsboard-server:latest
COPY thingsboard-4.0.rpm /tmp/
RUN rpm -Uvh /tmp/thingsboard-4.0.rpm \
 && /usr/share/thingsboard/bin/install/upgrade.sh \
 && rm /tmp/thingsboard-4.0.rpm
CMD ["java","-jar","/usr/share/thingsboard/bin/thingsboard.jar"]
