# Dockerfile-4.0.0
FROM rockylinux:9

# Install dependencies
RUN dnf install -y wget rpm java-17-openjdk net-tools && dnf clean all

WORKDIR /tmp

# Copy RPM (make sure you download the RPM to this directory first!)
COPY thingsboard.rpm .

# Install ThingsBoard
RUN rpm -Uvh thingsboard.rpm && rm -f thingsboard.rpm

EXPOSE 8080

CMD ["java", "-jar", "/usr/share/thingsboard/bin/thingsboard.jar"]

